
  CREATE TABLE "ORAVCS_METADATA" 
   (	"ID" NUMBER, 
	"SCHEMA" VARCHAR2(30), 
	"CREATED_AT" TIMESTAMP (6), 
	"MD" CLOB, 
	"XML" "XMLTYPE", 
	"OBJ_NAME" VARCHAR2(255), 
	"OBJ_TYPE" VARCHAR2(255)
   ) ;
