WHENEVER OSERROR EXIT 1
WHENEVER SQLERROR EXIT 2
@SEQUENCE/ORAVCS_LOG_SEQ.sql
@SEQUENCE/ORAVCS_SEQ.sql
@TABLE/ORAVCS_LOG.sql
@TABLE/ORAVCS_METADATA.sql
@PROCEDURE/ORAVCS_LOGGER.sql
@PROCEDURE/ORAVCS_PROCESS.sql
EXIT 0
